all: README.md

README.md:
	touch README.md
	echo "#The Unix Workbench Project#" > README.md
	echo "" >> README.md
	echo "Auto generated by makefile in *$(shell date)*" >> README.md
	echo "" >> README.md
	echo "guessinggame.sh have **$(shell cat guessinggame.sh | wc -l|sed 's/ //g')** lines" >> README.md
